---
version: "3"
services:
  algorithm_00:
    container_name: algorithm00
    network_mode: "host"
    build:
      context: ./containers/00_container1
      dockerfile: Dockerfile

  algorithm_01:
    container_name: algorithm01
    network_mode: "host"
    build:
      context: ./containers/01_container2
      dockerfile: Dockerfile