---
version: "3"

services:
  api:
    container_name: api
    image: krisboorger/adnotacja-api:latest
    restart: unless-stopped
    network_mode: host
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    network_mode: host
